---
- name: Install Nginx Web Server
  hosts: webservers
  become: yes
  tasks:
    - name: Install EPEL repository
      dnf:
        name: epel-release
        state: present

    - name: Install nginx
      dnf:
        name: nginx
        state: present

    - name: Start and enable nginx service
      systemd:
        name: nginx
        state: started
        enabled: yes

    - name: Create a simple HTML page
      copy:
        dest: /usr/share/nginx/html/index.html
        content: "<h1>Welcome to Ansible Managed Nginx Server!</h1>"
        owner: nginx
        group: nginx
        mode: '0644'

    - name: Ensure firewall allows HTTP and HTTPS traffic
      firewalld:
        service: "{{ item }}"
        permanent: yes
        state: enabled
      loop:
        - http
        - https

    - name: Reload firewall
      firewalld:
        state: reloaded
